### ISSUE TITLE
Floating-point exception

### ISSUE THREAD

**Issue by andygongyb** [HewlettPackard/cacti#10]
Hi,

I tried to run the latest build with the example config files, but I got floating-point exceptions. I have tried building the binary with GCC 4.9 and GCC 6.5, and both compilations had the same problem.

Here is the GDB backtrace log from running ./cacti -infile 2DDRAM_micron1Gb.cfg. I appreciate it if you could provide any insight on it!

Program received signal SIGFPE, Arithmetic exception.
0x000000000045e321 in IOTechParam::IOTechParam (this=0x6aa0b0, g_ip=0x0, io_type1=32767, num_mem_dq=-56112, mem_data_width=0, num_dq=6987952, connection=0, num_loads=1, freq=0)
    at extio_technology.cc:918
918                     (num_dq/mem_data_width)/(g_ip->num_clk/2);
(gdb) bt
#0  0x000000000045e321 in IOTechParam::IOTechParam (this=0x6aa0b0, g_ip=0x0, io_type1=32767, num_mem_dq=-56112, mem_data_width=0, num_dq=6987952, connection=0, num_loads=1, freq=0)
    at extio_technology.cc:918
#1  0x000000000041f530 in cacti_interface (infile_name=...) at io.cc:1292
#2  0x0000000000411e64 in main (argc=0, argv=0x0) at main.cc:78

Thanks,
Andy

**Comment by robin-tukl** [comment]
Hi Andy, 
that is maybe because of some uninitialized variables that were introduced during the io update. What works for me, was to add everything after line 185 from the chache.cfg.
Best regards,
Yannick

**Comment by andygongyb** [comment]
Thank you! I used the chache.cfg and it works!
