### ISSUE TITLE
Web interface/demo is no longer available.

### ISSUE THREAD

**Issue by woo2** [HewlettPackard/cacti#4]
Hi, I don't know if this is out of the scope of this repo, but I noticed that the web interface at [http://quid.hpl.hp.com:9081/cacti/](http://quid.hpl.hp.com:9081/cacti/) is no longer running and I wanted to make sure someone knows about it.

**Comment by nicmcd** [comment]
The web interface was taken down. It was often out of date. I recommend using the newest version in the repo.
